eatapp/urls.py
from django.urls import path
from . import views
from .views import EatLogin, EatRegister, EatCreate
from .views import htmx_delete_course, htmx_create_dose, htmx_delete_dose, htmx_create_dose_auto, logout_view, htmx_create_kid, htmx_delete_kid
from .views import BetaCreateCourse, BetaCreateDose, BetaViewCourse, BetaMain, BetaDeleteCourse, BetaUpdateCourse, betapatientupdate

urlpatterns = [
    path('login/', EatLogin.as_view(), name='eatlogin'),
    path('logout/', views.logout_view, name='eatlogout'),
    path('register/', EatRegister.as_view(), name='eatregister'),
]

newversion = [
    path('', BetaMain.as_view(), name='betamain'),
    path('course/<int:pk>/', BetaViewCourse.as_view(), name="betaviewcourse"),
    path('course/create/', BetaCreateCourse.as_view(), name="betacreatecourse"),
    path('course/dose/create/', BetaCreateDose.as_view(), name="betacreatedose"),
    path('course/<int:pk>/delete_p/',
         BetaDeleteCourse.as_view(), name="betadelete"),
    path('course/<int:pk>/update/',
         BetaUpdateCourse.as_view(), name='betaupdatecourse'),
    path('profile/', views.betapatientupdate, name='betapatientupdate'),
]

htmxpatterns = [
    path('course/<int:id>/add/', views.htmx_create_dose, name="htmx_create_dose"),
    path('view_course/<int:id>/addauto/',
         views.htmx_create_dose_auto, name="htmx_create_dose_auto"),
    path('course/<int:id>/delete/', views.htmx_delete_course,
         name="htmx_delete_course"),
    path('course/view/<int:id>/delete/<int:doseid>/',
         views.htmx_delete_dose, name="htmx_delete_dose"),
    path('profile/create_kid/', views.htmx_create_kid, name="htmx_create_kid"),
    path('profile/delete_kid/<int:kidid>',
         views.htmx_delete_kid, name="htmx_delete_kid"),
]

urlpatterns = urlpatterns + newversion + htmxpatterns

eatyourmeds/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('eatapp.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

eatapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import datetime, timedelta

# Create your models here.

medicine_choices = [
    ('Ibuprofen', 'Ibuprofen'),
    ('Paracetamol', 'Paracetamol'),
    ('Zyrtec', 'Zyrtec'),
    ('Cetirizine', 'Cetirizine'),
    ('Promethazine', 'Promethazine'),
    ('Ivy Leaf Extract', 'Ivy Leaf Extract'),
]

# rec_interval, description, used for, sideeffects, brandname
# medicine_info = (
#     "Cetirizine", [4, 
#                    "Cetirizine is an antihistamine used to relieve allergy symptoms such as watery eyes, runny nose, itching eyes/nose, sneezing, hives, and itching. It works by blocking a certain natural substance (histamine) that your body makes during an allergic reaction. Cetirizine does not prevent hives or prevent/treat a serious allergic reaction (such as anaphylaxis).",
#                    "relieve allergy symptoms such as watery eyes, runny nose, itching eyes/nose, sneezing, hives, and itching.",
#                    "Allergy symptoms such as watery eyes, runny nose, itching eyes/nose, sneezing, hives, and itching",	"Drowsiness, tiredness, and dry mouth may occur. Stomach pain may also occur, especially in children. If any of these effects last or get worse, tell your doctor or pharmacist promptly",	
#                    "Zyrtec"],
#     "Paracetamol", [6,
#                     "Paracetamol is an analgesic and antipyretic drug that is used to temporarily relieve mild-to-moderate pain and fever. It is commonly included as an ingredient in cold and flu medications and is also used on its own.",
#                     "Mild to moderate pain (from headaches, menstrual periods, toothaches, backaches, osteoarthritis, or cold/flu aches and pains) and to reduce fever.",
#                     "Usually has no side effects.",
#                     "Panadol"],
#     "Promethazine", [6,
#                     "Promethazine is an antihistamine and works by blocking a certain natural substance (histamine) that your body makes during an allergic reaction. Its other effects (such as anti-nausea, calming, pain relief) may work by affecting other natural substances (such as acetylcholine) and by acting directly on certain parts of the brain.",
#                     "Prevent and treat nausea and vomiting related to certain conditions (such as before/after surgery, motion sickness). It is also used to treat allergy symptoms such as rash, itching, and runny nose.",	
#                     "Drowsiness, dizziness, constipation, blurred vision, or dry mouth may occur. If any of these effects last or get worse, tell your doctor.",
#                     "Promethazine"],
#     "Ivy Leaf Extract", [8,
#                     "Ivy Leaf extract might improve lung function in people with breathing difficulty. English ivy might also have antioxidant effects.	Ivy Leaf extract might help thin mucus in the airways.",	
#                     "Nausea, vomiting and diarrhea",	
#                     "Prospan, Abrilar"],
# )

class MedicalInfo(models.Model):
    medicine = models.CharField(max_length=50, choices=medicine_choices)
    rec_interval = models.IntegerField(null=False)
    description = models.TextField(max_length=500)
    used_for = models.TextField(max_length=500, default="")
    sideeffects = models.TextField(max_length=500)
    brandname = models.TextField(max_length=500, default="", null=True)

    def __str__(self):
        return self.medicine


class EatModel(models.Model):

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    medicine = models.ForeignKey(
        MedicalInfo, on_delete=models.SET_NULL, null=True)
    interval = models.IntegerField(default=4)
    last_fed = models.DateTimeField(default=datetime.now)
    second_dose = models.DateTimeField(default=None, null=True)
    third_dose = models.DateTimeField(default=None, null=True)
    fourth_dose = models.DateTimeField(default=None, null=True)
    fifth_dose = models.DateTimeField(default=None, null=True)
    remarks = models.TextField(max_length=140, blank=True)
    complete = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.id)

    @property
    def get_second_dose(self):
        a = self.last_fed + timedelta(hours=self.interval)
        return a

    @property
    def get_third_dose(self):
        b = self.last_fed + timedelta(hours=self.interval) * 2
        return b

    @property
    def get_fourth_dose(self):
        c = self.last_fed + timedelta(hours=self.interval) * 3
        return c

    @property
    def get_fifth_dose(self):
        d = self.last_fed + timedelta(hours=self.interval) * 4
        return d

    def save(self, *args, **kwargs):
        self.second_dose = self.get_second_dose
        self.third_dose = self.get_third_dose
        self.fourth_dose = self.get_fourth_dose
        self.fifth_dose = self.get_fifth_dose
        super(EatModel, self).save(*args, **kwargs)

    class Meta:
        ordering = ['complete']  # ordering in descending just do -complete


class Patient(models.Model):
    name = models.CharField(max_length=50, blank=True, null=True, default=None)
    parent = models.ForeignKey(
        User, blank=True, null=True, default=None, on_delete=models.CASCADE)
    hehe = models.CharField(max_length=50, blank=True, null=True, default=None)

    def __str__(self):
        return str(self.name)


class CourseInfo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=False)
    medicine = models.ForeignKey(
        MedicalInfo, on_delete=models.SET_NULL, null=True)
    interval = models.IntegerField(default=4)
    course_duration = models.IntegerField(default=3)
    course_start = models.DateTimeField(default=datetime.now)
    complete = models.BooleanField(default=False)
    course_created = models.DateTimeField(auto_now_add=True)
    patient = models.ForeignKey(
        Patient, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return str(self.id)


class DoseInfo(models.Model):
    courseinfo = models.ForeignKey(
        CourseInfo, on_delete=models.CASCADE, default='')
    dose_timing = models.DateTimeField(default=datetime.now)
    dose_created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['dose_timing']

    def __str__(self):
        return str(self.id)

eatapp/forms.py
from django import forms
from .models import CourseInfo, DoseInfo, Patient
# crispy forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, Field,  Submit, Reset, Div, Button
from crispy_forms.bootstrap import AppendedText, PrependedText, FormActions
from django.utils.safestring import mark_safe
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
# from django.urls import reverse_lazy, reverse


class BetaCourseForm(forms.ModelForm):
    class Meta:
        fields = ['medicine', 'interval',
                  'course_duration', 'course_start', 'patient']
        model = CourseInfo
        labels = {
            'interval': 'Number of hours in between each dose:',
            'course_duration': 'Number of days to take the medicine:',
            'course_start': 'Date/time you first ate the medicine:',
            "patient": "Who's eating the medicine?",
        }

    def __init__(self, user=None, *args, **kwargs):
        self.patient = Patient.objects.filter(parent=user)
        super(BetaCourseForm, self).__init__(*args, **kwargs)
        self.fields['patient'].queryset = self.patient
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Fieldset(
                'Hi {{form_user}}! Let\'s start with some details of your medicine:',
            ),
            Div(
                Div('medicine', css_class='col-sm-6'),
                Div('patient', css_class='col-sm-6'),
                css_class='row pt-3 pb-4',
            ),
            Div(
                Div(AppendedText('interval', 'hours'), css_class='col-sm-6'),
                Div(AppendedText('course_duration', 'days'), css_class='col-sm-6'),
                css_class='row pb-4',
            ),
            Div(
                Field('course_start', id='id_course_start'),
                css_class='row pb-4',
            ),
            FormActions(
                Submit('submit', 'Submit', css_class='text-white fw-bold'),
                Reset('cancel', 'Cancel', css_class='btn btn-outline-secondary'),
            ),
        )


class BetaDoseForm(forms.ModelForm):
    class Meta:
        fields = "__all__"
        model = DoseInfo


class BetaDoseHtmxForm(forms.ModelForm):
    class Meta:
        fields = ['dose_timing']
        model = DoseInfo


class BetaDoseAutoForm(forms.ModelForm):
    class Meta:
        fields = []
        model = DoseInfo


class BetaUserCreateForm(UserCreationForm):

    email = forms.EmailField(required=False)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Div(
                'username',
                css_class='row pb-4',
            ),
            Div(
                'email',
                css_class='row pb-4',
            ),
            Div(
                Div(
                    AppendedText('password1', mark_safe(
                        '<i class="bi bi-eye-slash" id="togglePassword1"></i>')),
                    css_class='col-sm-6',
                    id='#id_password1',
                ),
                Div(
                    AppendedText('password2', mark_safe(
                        '<i class="bi bi-eye-slash" id="togglePassword2"></i>')),
                    css_class='col-sm-6',
                    id='#id_password2',
                ),
                css_class='row pb-4',
            ),
            FormActions(
                Submit('submit', 'Submit', css_class='text-white fw-bold'),
                Reset('cancel', 'Cancel', css_class='btn btn-outline-secondary'),
            ),
        )


class BetaLoginForm(AuthenticationForm):

    class Meta:
        fields = ['username', 'password']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Div(
                css_class='row',
            ),
            Div(
                'username',
                css_class='col pb-4',
            ),
            Div(
                css_class='row',
            ),
            Div(
                Div(
                    AppendedText('password', mark_safe(
                        '<i class="bi bi-eye-slash" id="togglePassword1"></i>')),
                ),
                css_class='col pb-4',
            ),
            FormActions(
                Submit('submit', 'Login', css_class='text-white fw-bold'),
                Reset('cancel', 'Cancel', css_class='btn btn-outline-secondary'),
            ),
        )


class BetaPatientUpdateForm(forms.ModelForm):

    name = forms.CharField(required=True)

    class Meta:
        model = Patient
        fields = ['name', 'parent']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_show_labels = False
        self.helper.layout = Layout(
            Div(
                Div(
                    css_class='col-2',
                ),
                Div(
                    Field('name', placeholder='Add a name'),
                    css_class='col-4',
                ),
                Div(
                    Submit('submit', 'Add Kid', css_class='text-white fw-bold'),
                    Reset('cancel', 'Cancel',
                          css_class='btn btn-outline-secondary'),
                    css_class='col-4',
                ),
                Div(
                    css_class='col-2',
                ),
                css_class="row g-2",
            )
        )

templates/eatapp/JStest.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>

    <div class="row bg-light border border-success rounded p-1 mt-3">
        <div class="col-sm-3">
            <h3><strong><a href="/eatyourmeds/dose/34/">Ibuprofen</a></strong></h3>
            <i class="bi bi-clock-fill"></i>&nbsp;&nbsp;24 hourly
        </div>
        <div class="col-sm-9 d-flex justify-content-start align-items-end border-start-dark">
            <div class="flex-grow-1">
                <ul class="list-group list-group-horizontal-sm">
                    <li class="list-group-item" id="34-last-fed"><a href="/eatyourmeds/dose/34/" class="link-no-line"><i class="bi bi-1-circle-fill"></i>&nbsp;06 Dec, 10:17 a.m.</li>
                    
                    <li class="list-group-item" id="34-second-dose"><a href="/eatyourmeds/dose/34/" class="link-no-line"><i class="bi bi-2-circle-fill"></i>&nbsp;07 Dec, 10:17 a.m.</li>
                    
                    
                    <li class="list-group-item" id="34-third-dose"><a href="/eatyourmeds/dose/34/" class="link-no-line"><i class="bi bi-4-circle-fill"></i>&nbsp;&nbsp;08 Dec, 10:17 a.m.</li>
                    
                    
                    <li class="list-group-item" id="34-fourth-dose"><a href="/eatyourmeds/dose/34/" class="link-no-line"><i class="bi bi-4-circle-fill"></i>&nbsp;&nbsp;09 Dec, 10:17 a.m.</li>        
                    
                </ul>
            </div>
            <div>            
                <a hx-delete="/eatyourmeds/dose/34/delete/" href="#" class="dropdown-item"><i class="bi bi-trash3"></i></a>
            </div>

        </div>
    </div>

    <script>
        const change = document.getElementsbyClassName("list-group-item")
        
    </script>
</body>
</html>

templates/eatapp/beta_create_dose.html
<!-- <form action="" method="POST">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Submit"></p>
    </form> -->

templates/eatapp/beta_update_patient.html
{% extends 'eatapp/base.html' %}
{% block content %}

{% load crispy_forms_tags %}
<div class="container px-4">
    <div class="row mt-5">
        <div class="col-sm">
            <nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='%236c757d'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
                <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'betamain' %}">Home</a></li>
                <li class="breadcrumb-item active" aria-current="page">Update Profile</li>
                </ol>
            </nav>
        </div>
    </div>
    <h2 class="text-center mb-5 mt-5">Add names of people taking the medicine</h2>
    <div class="row mb-3">
        <div class="col-2">
        </div>
        <div class="col-8">
            <p>This is useful if you have a few kids eating the same medication.</p> 
            <p>If it's just you, <a href="{% url 'betacreatecourse' %}">skip this and start creating a new course of medicine</a>.</p>        
        </div>
        <div class="col-2">
        </div>
    </div>
    <div class="row">
        <div class="col-2">
        </div>
        <div class="col-8 text-start">
            <form hx-post="{% url 'htmx_create_kid' %}" hx-target="#htmx_view_kid" hx-swap="innerHTML">
                {% crispy form %}
            </form>
        </div>
        <div class="col-2">
        </div>
    </div>
    <div class="row">
        <div class="col-2"></div>
        <div class="col-8 mt-4" id="htmx_view_kid">
            <hr>
            {% include './htmx_view_kid.html' %}
        </div>
        <div class="col-2"></div>
    </div>
</div>
{% endblock %}

templates/eatapp/beta_view_course.html
{% extends 'eatapp/base.html' %}

{% block content %}
<div class="container px-4">
    <div class="row mt-5">
        <div class="col-sm">
            <nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='%236c757d'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
                <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'betamain' %}">Home</a></li>
                <li class="breadcrumb-item"><a href="{% url 'betaviewcourse' courseinfo.0.id %}">View Course</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{courseinfo.0.medicine}} (started {{courseinfo.0.course_start|date:"j M"}})</li>
                </ol>
            </nav>
        </div>
    </div>

    {% for item in courseinfo %}
    <div class="row mt-5">
        <div class="col-sm">
            <h2 class="d-inline-flex mb-4"><i class="bi bi-1-square-fill"></i>&nbsp;Course Details</h2>
            <span>
                <a href="{% url 'betaupdatecourse' courseinfo.0.pk %}"><i class="bi bi-pencil-fill ms-4 me-2 text-dark"></i></a>
                <a href="{% url 'betadelete' courseinfo.0.pk %}"><i class="bi bi-trash3 text-danger"></i></a>
            </span>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-4 px-2 mb-3">
            <div class="card border-secondary-subtle h-100">
                <div class="card-body d-flex justify-content-around align-items-center">
                    <div><i class="bi bi-capsule-pill fs-1"></i></div>
                    
                    <div class="text-center">
                        <h4 class="card-title fw-bold border-bottom border-dark">Medicine</h4>
                        <div class="card-text">
                        {% if item.patient is None %}
                        {{item.medicine}}
                        {% else %}
                        {{item.medicine}} for {{item.patient}}
                        {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-8 px-2 mb-3">
            <div class="card border-secondary-subtle h-100">
                <div class="card-body">
                    <div class="text-center">
                        <h4 class="card-title fw-bold border-bottom border-dark">Progress</h4>
                        <div class="card-text">
                            <div class="progress" role="progressbar" aria-label="Info example" aria-valuenow="{{progress}}" aria-valuemin="0" aria-valuemax="100" style="height: 1.75em">
                                <div class="progress-bar progress-bar-striped" style="width: {{progress}}%"><span class="fs-6 text-dark text-white"><strong>{{progress}}%</strong></span></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-4 px-2 mb-3">
            <div class="card border-secondary-subtle h-100">
                <div class="card-body d-flex justify-content-around align-items-center">
                    <div><i class="bi bi-calendar-date fs-1"></i></div>
                    <div class="text-center">
                        <h4 class="card-title fw-bold border-bottom border-dark">Course Start</h4>
                        <div class="card-text">{{item.course_start|date:"j M (D)"}} {{item.course_start|time:"g:i a"}}</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-4 px-2 mb-3">
            <div class="card border-secondary-subtle h-100">
                <div class="card-body d-flex justify-content-around align-items-center">
                    <div><i class="bi bi-calendar-range fs-1"></i></div>
                    <div class="text-center">
                        <h4 class="card-title fw-bold border-bottom border-dark">Course Duration</h4>
                        <div class="card-text">{{item.course_duration}} days</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-4 px-2 mb-3">
            <div class="card border-secondary-subtle h-100">
                <div class="card-body d-flex justify-content-around align-items-center">
                    <div><i class="bi bi-clock-history fs-1"></i></div>
                    <div class="text-center">
                        <h4 class="card-title fw-bold border-bottom border-dark">Interval</h4>
                        <div class="card-text">{{item.interval}} hourly per dose</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end card -->
    {% endfor %}

    <div class="row g-0">

        <h2 class="mb-4 mt-5" id="adddosetiming"><i class="bi bi-2-square-fill"></i>&nbsp;Add Dose Timings</h2>
        <div class="d-flex justify-content-center align-items-center border border-secondary-subtle rounded mt-2 pt-3 pb-3">    
            <div class="col-sm-4 text-center">
                <form action="{% url 'htmx_create_dose_auto' courseinfo.0.id %}" method="POST">
                    {% csrf_token %}
                    <input type="submit" class="btn btn-primary rounded-pill fw-bold px-3 text-white" value="Automatic Add Doses">
                    <i class="bi bi-question-circle-fill text-secondary fs-5" data-bs-toggle="tooltip" title="Fill in your doses using course start date, interval and duration you already provided"></i>
                </form>
            </div>
            <div class="col-sm-3 ps-5 text-center">
                <span class="btn btn-secondary rounded-pill text-white"><strong>OR</strong></span>
            </div>
            <div class="col-sm-3">
                <form hx-post="{% url 'htmx_create_dose' courseinfo.0.id %}" hx-target="#htmx_view_dose" hx-swap="innerHTML">
                    {% csrf_token %}
                    {{htmx_create_dose.dose_timing}}
            </div>
            <div class="col-sm-2">
                <input type="submit" class="btn btn-primary rounded-pill fw-bold px-3 text-white" value="Add">
                </form>
            </div>
        </div>
    </div>
    <div class="row g-0 ">
            <h2 class="mb-4 mt-5"><i class="bi bi-3-square-fill"></i>&nbsp;View Dose Timings</h2>
            <div id="htmx_view_dose" class="mt-2 pt-2">
                {% include 'eatapp/htmx_view_dose.html' %}
            </div>
            <div class="accordion mt-3" id="dosecalendar">
                <div class="accordion-item border-secondary-subtle">
                    <h2 class="accordion-header">
                    <button class="accordion-button collapsed bg bg-light-subtle text-emphasis-secondary" type="button" data-bs-toggle="collapse" data-bs-target="#calviewOne" aria-expanded="true" aria-controls="calviewOne">
                        <strong>Calendar View</strong>
                    </button>
                    </h2>
                    <div id="calviewOne" class="accordion-collapse collapse" data-bs-parent="#calview">
                        <div class="accordion-body">
                            <div class="table-responsive-sm">
                                {% if not calendar %}
                                <p class="d-flex justify-content-around align-items-center">Oops, there's no data here yet. Start by adding timings above.</p>
                                {% else %}
                                {{calendar}}
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </div>
    
    <h2 class="mb-4 mt-5"><i class="bi bi-4-square-fill"></i>&nbsp;Medicine Information</h2>
    {% for item in courseinfo %}
    <div class="accordion" id="medinfo">
        <div class="accordion-item border-secondary-subtle">
            <h2 class="accordion-header">
            <button class="accordion-button collapsed bg bg-light-subtle text-emphasis" type="button" data-bs-toggle="collapse" data-bs-target="#medinfoOne" aria-expanded="true" aria-controls="medinfoOne">
                <strong>{{item.medicine}}</strong>
            </button>
            </h2>
            <div id="medinfoOne" class="accordion-collapse collapse" data-bs-parent="#medinfo">
                <div class="accordion-body">
                    <div class="row mb-3">
                        <div class="col-sm-8">
                            <div class="card border-secondary h-100">
                                <div class="card-body d-flex justify-content-around align-items-center">
                                    <div><i class="bi bi-body-text fs-1"></i></div>
                                    <div class="text-center ps-4">
                                        <h4 class="card-title fw-bold border-bottom border-dark">Description</h4>
                                        <div class="card-text">{{item.medicine.description}}</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="card border-secondary h-100">
                                <div class="card-body d-flex justify-content-around align-items-center">
                                    <div><i class="bi bi-exclamation-triangle fs-1"></i></div>
                                    <div class="text-center">
                                        <h4 class="card-title fw-bold border-bottom border-dark">Side Effects</h4>
                                        <div class="card-text">{{item.medicine.sideeffects}}</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-4">
                            <div class="card border-secondary h-100">
                                <div class="card-body d-flex justify-content-around align-items-center">
                                    <div><i class="bi bi bi-magic fs-1"></i></div>
                                    <div class="text-center">
                                        <h4 class="card-title fw-bold border-bottom border-dark">Usage</h4>
                                        <div class="card-text">{{item.medicine.used_for}}</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="card border-secondary h-100">
                                <div class="card-body d-flex justify-content-around align-items-center">
                                    <div><i class="bi bi-clock-history fs-1"></i></div>
                                    <div class="text-center">
                                        <h4 class="card-title fw-bold border-bottom border-dark">Interval</h4>
                                        <div class="card-text">{{item.medicine.rec_interval}} hourly per dose</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="card border-secondary h-100">
                                <div class="card-body d-flex justify-content-around align-items-center">
                                    <div><i class="bi bi-clock-history fs-1"></i></div>
                                    <div class="text-center">
                                        <h4 class="card-title fw-bold border-bottom border-dark">Brand Names</h4>
                                        <div class="card-text">{{item.medicine.brandnames}}</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script>
    flatpickr('#id_dose_timing', {
        enableTime: true,
        altInput: true,
        altFormat: "j F Y, h:i K",
        dateFormat: "Y-m-d H:i",
    });

    const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
    const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
</script>
{% endblock %}

templates/eatapp/test.html
{{start_date}}
{{course_duration}}
{{number_of_courses}}

{{new_doses}}
<p>{{count}}</p>